var path = require('path')
const returnImageString = (race, building) => {
  //Buildings are lowercase
  var imgPath = `https://s3.us-west-2.amazonaws.com/needmorelumberassets/buildings/${race}/${building}.png`
  return imgPath;
};

const data = {
  "N/A": {    
      "Gold": "N/A",
      "Lumber": "N/A",
      "Supply": "N/A",
      "Hit Points": "N/A",
      "Maximum Hit Points": "N/A",
      "Armor Type": "N/A",
      "Armor": "N/A",
      "Maximum Armor": "N/A",
      "Day Sight": "N/A",
      "Night Sight": "N/A",
      "Speed": "N/A",
      "Build Time": "N/A",
      "Attack Type": "N/A",
      "Weapon Type": "N/A",
      "Ground Attack": "N/A",
      "Maximum Ground Attack": "N/A",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "None",
      "Maximum Air Attack": "None",
      "Cooldown": "N/A",
      "Range": "N/A",
      "Maximum Range": "N/A",
      "Race": "N/A",
      "Animation": "",
      "Portrait": ""
  },
  "Human": {
    "Town Hall": {
      "Unit": "Town Hall",
      "Gold": "385",
      "Lumber": "205",
      "Build Time": "180",
      "Portrait": returnImageString('Human', 'townhall')
    },
    "Keep": {
      "Unit": "Keep",
      "Gold": "320",
      "Lumber": "210",
      "Build Time": "140",
      "Portrait": returnImageString('Human', 'keep')
    },
    "Castle": {
      "Unit": "Castle",
      "Gold": "360",
      "Lumber": "210",
      "Build Time": "140",
      "Portrait": returnImageString('Human', 'castle')
    },
    "Barracks": {
      "Unit": "Barracks",
      "Gold": "160",
      "Lumber": "60",
      "Build Time": "60",
      "Portrait": returnImageString('Human', 'barracks')
    },
    "Farm": {
      "Unit": "Farm",
      "Gold": "80",
      "Lumber": "20",
      "Build Time": "35",
      "Portrait": returnImageString('Human', 'farm')
    },
    "Altar of Kings": {
      "Unit": "Altar of Kings",
      "Gold": "180",
      "Lumber": "50",
      "Build Time": "180",
      "Portrait": returnImageString('Human', 'altarofkings')
    },
    "Lumber Mill": {
      "Unit": "Lumber Mill",
      "Gold": "120",
      "Lumber": "0",
      "Build Time": "60",
      "Portrait": returnImageString('Human', 'lumbermill')
    },
    "Scout Tower": {
      "Unit": "Farm",
      "Gold": "30",
      "Lumber": "20",
      "Build Time": "35",
      "Portrait": returnImageString('Human', 'scouttower')
    },
    "Blacksmith": {
      "Unit": "Blacksmith",
      "Gold": "140",
      "Lumber": "60",
      "Build Time": "70",
      "Portrait": returnImageString('Human', 'blacksmith')
    },
    "Workshop": {
      "Unit": "Workshop",
      "Gold": "140",
      "Lumber": "140",
      "Build Time": "60",
      "Portrait": returnImageString('Human', 'workshop')
    },
    "Arcane Sanctum": {
      "Unit": "Farm",
      "Gold": "150",
      "Lumber": "140",
      "Build Time": "70",
      "Portrait": returnImageString('Human', 'arcanesanctum')
    },
    "Gryphon Avlary": {
      "Unit": "Farm",
      "Gold": "140",
      "Lumber": "150",
      "Build Time": "75",
      "Portrait": returnImageString('Human', 'gryphonavlary')
    },
    "Peasant": {
      "Unit": "Peasant",
      "Gold": "75",
      "Lumber": "0",
      "Supply": "1",
      "Hit Points": "220",
      "Maximum Hit Points": "220",
      "Armor Type": "Medium",
      "Armor": "0",
      "Maximum Armor": "0",
      "Day Sight": "80",
      "Night Sight": "60",
      "Speed": "190",
      "Build Time": "15",
      "Attack Type": "Normal",
      "Weapon Type": "Normal",
      "Ground Attack": "5.5",
      "Maximum Ground Attack": "5.5",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "None",
      "Maximum Air Attack": "None",
      "Cooldown": "2",
      "Range": "Melee",
      "Maximum Range": "Melee",
      "Race": "Human",
      "Animation": "http://classic.battle.net/war3/images/human/units/animations/peasant.gif",
      "Portrait": "http://classic.battle.net/war3/images/human/units/portraits/peasant.gif"
    },
    "Militia": {
      "Unit": "Militia",
      "Gold": "None",
      "Lumber": "None",
      "Supply": "1",
      "Hit Points": "220",
      "Maximum Hit Points": "220",
      "Armor Type": "Heavy",
      "Armor": "4",
      "Maximum Armor": "0",
      "Day Sight": "140",
      "Night Sight": "80",
      "Speed": "270",
      "Build Time": "N/A",
      "Attack Type": "Normal",
      "Weapon Type": "Normal",
      "Ground Attack": "12.5",
      "Maximum Ground Attack": "17",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "None",
      "Maximum Air Attack": "None",
      "Cooldown": "1.2",
      "Range": "Melee",
      "Maximum Range": "Melee",
      "Race": "Human",
      "Animation": "http://classic.battle.net/war3/images/human/units/animations/militia.gif",
      "Portrait": "http://classic.battle.net/war3/images/human/units/portraits/militia.gif"
    },
    "Footman": {
      "Unit": "Footman",
      "Gold": "135",
      "Lumber": "0",
      "Supply": "2",
      "Hit Points": "420",
      "Maximum Hit Points": "420",
      "Armor Type": "Heavy",
      "Armor": "2",
      "Maximum Armor": "8",
      "Day Sight": "140",
      "Night Sight": "80",
      "Speed": "270",
      "Build Time": "20",
      "Attack Type": "Normal",
      "Weapon Type": "Normal",
      "Ground Attack": "12.5",
      "Maximum Ground Attack": "17",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "None",
      "Maximum Air Attack": "None",
      "Cooldown": "1.35",
      "Range": "Melee",
      "Maximum Range": "Melee",
      "Race": "Human",
      "Animation": "http://classic.battle.net/war3/images/human/units/animations/footman.gif",
      "Portrait": "http://classic.battle.net/war3/images/human/units/portraits/footman.gif"
    },
    "Rifleman": {
      "Unit": "Rifleman",
      "Gold": "205",
      "Lumber": "30",
      "Supply": "3",
      "Hit Points": "535",
      "Maximum Hit Points": "535",
      "Armor Type": "Medium",
      "Armor": "0",
      "Maximum Armor": "6",
      "Day Sight": "140",
      "Night Sight": "80",
      "Speed": "270",
      "Build Time": "26",
      "Attack Type": "Pierce",
      "Weapon Type": "Instant",
      "Ground Attack": "21",
      "Maximum Ground Attack": "28.5",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "21",
      "Maximum Air Attack": "28.5",
      "Cooldown": "1.5",
      "Range": "40",
      "Maximum Range": "60",
      "Race": "Human",
      "Animation": "http://classic.battle.net/war3/images/human/units/animations/rifleman.gif",
      "Portrait": "http://classic.battle.net/war3/images/human/units/portraits/rifleman.gif"
    },
    "Knight": {
      "Unit": "Knight",
      "Gold": "245",
      "Lumber": "60",
      "Supply": "4",
      "Hit Points": "835",
      "Maximum Hit Points": "985",
      "Armor Type": "Heavy",
      "Armor": "5",
      "Maximum Armor": "11",
      "Day Sight": "140",
      "Night Sight": "80",
      "Speed": "350",
      "Build Time": "45",
      "Attack Type": "Normal",
      "Weapon Type": "Normal",
      "Ground Attack": "34",
      "Maximum Ground Attack": "43",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "None",
      "Maximum Air Attack": "None",
      "Cooldown": "1.4",
      "Range": "Melee",
      "Maximum Range": "Melee",
      "Race": "Human",
      "Animation": "http://classic.battle.net/war3/images/human/units/animations/knight.gif",
      "Portrait": "http://classic.battle.net/war3/images/human/units/portraits/knight.gif"
    },
    "Priest": {
      "Unit": "Priest",
      "Gold": "135",
      "Lumber": "10",
      "Supply": "2",
      "Hit Points": "290",
      "Maximum Hit Points": "370",
      "Armor Type": "Unarmored",
      "Armor": "0",
      "Maximum Armor": "0",
      "Day Sight": "140",
      "Night Sight": "80",
      "Speed": "270",
      "Build Time": "28",
      "Attack Type": "Magic",
      "Weapon Type": "Missile",
      "Ground Attack": "8.5",
      "Maximum Ground Attack": "8.5",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "8.5",
      "Maximum Air Attack": "8.5",
      "Cooldown": "2",
      "Range": "60",
      "Maximum Range": "60",
      "Race": "Human",
      "Animation": "http://classic.battle.net/war3/images/human/units/animations/priest.gif",
      "Portrait": "http://classic.battle.net/war3/images/human/units/portraits/priest.gif"
    },
    "Sorceress": {
      "Unit": "Sorceress",
      "Gold": "155",
      "Lumber": "20",
      "Supply": "2",
      "Hit Points": "325",
      "Maximum Hit Points": "405",
      "Armor Type": "Unarmored",
      "Armor": "0",
      "Maximum Armor": "0",
      "Day Sight": "140",
      "Night Sight": "80",
      "Speed": "270",
      "Build Time": "30",
      "Attack Type": "Magic",
      "Weapon Type": "Missile",
      "Ground Attack": "11",
      "Maximum Ground Attack": "11",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "11",
      "Maximum Air Attack": "11",
      "Cooldown": "1.75",
      "Range": "60",
      "Maximum Range": "60",
      "Race": "Human",
      "Animation": "http://classic.battle.net/war3/images/human/units/animations/sorceress.gif",
      "Portrait": "http://classic.battle.net/war3/images/human/units/portraits/sorceress.gif"
    },
    "Spell Breaker": {
      "Unit": "Spell Breaker",
      "Gold": "215",
      "Lumber": "30",
      "Supply": "3",
      "Hit Points": "600",
      "Maximum Hit Points": "600",
      "Armor Type": "Medium",
      "Armor": "3",
      "Maximum Armor": "9",
      "Day Sight": "140",
      "Night Sight": "80",
      "Speed": "300",
      "Build Time": "28",
      "Attack Type": "Normal",
      "Weapon Type": "Missile",
      "Ground Attack": "14",
      "Maximum Ground Attack": "20",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "None",
      "Maximum Air Attack": "None",
      "Cooldown": "1.9",
      "Range": "25",
      "Maximum Range": "15",
      "Race": "Human",
      "Animation": "http://classic.battle.net/war3/images/human/units/animations/spellbreaker.gif",
      "Portrait": "http://classic.battle.net/war3/images/human/units/portraits/spellbreaker.gif"
    },
    "Flying Machine": {
      "Unit": "Flying Machine",
      "Gold": "90",
      "Lumber": "30",
      "Supply": "1",
      "Hit Points": "200",
      "Maximum Hit Points": "200",
      "Armor Type": "Heavy",
      "Armor": "2",
      "Maximum Armor": "8",
      "Day Sight": "180",
      "Night Sight": "110",
      "Speed": "400",
      "Build Time": "13",
      "Attack Type": "Siege/Pierce",
      "Weapon Type": "Missile/Instant",
      "Ground Attack": "7.5",
      "Maximum Ground Attack": "12",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "14.5",
      "Maximum Air Attack": "19",
      "Cooldown": "2.5/2",
      "Range": "Melee",
      "Maximum Range": "50",
      "Race": "Human",
      "Animation": "http://classic.battle.net/war3/images/human/units/animations/flyingmachine.gif",
      "Portrait": "http://classic.battle.net/war3/images/human/units/portraits/flyingmachine.gif"
    },
    "Mortar Team": {
      "Unit": "Mortar Team",
      "Gold": "180",
      "Lumber": "70",
      "Supply": "3",
      "Hit Points": "360",
      "Maximum Hit Points": "360",
      "Armor Type": "Heavy",
      "Armor": "0",
      "Maximum Armor": "6",
      "Day Sight": "140",
      "Night Sight": "120",
      "Speed": "270",
      "Build Time": "40",
      "Attack Type": "Siege",
      "Weapon Type": "Artillery",
      "Ground Attack": "58",
      "Maximum Ground Attack": "79",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "None",
      "Maximum Air Attack": "None",
      "Cooldown": "3.5",
      "Range": "25",
      "Maximum Range": "115",
      "Race": "Human",
      "Animation": "http://classic.battle.net/war3/images/human/units/animations/mortarteam.gif",
      "Portrait": "http://classic.battle.net/war3/images/human/units/portraits/mortarteam.gif"
    },
    "Siege Engine": {
      "Unit": "Siege Engine",
      "Gold": "195",
      "Lumber": "60",
      "Supply": "3",
      "Hit Points": "700",
      "Maximum Hit Points": "700",
      "Armor Type": "Fort",
      "Armor": "2",
      "Maximum Armor": "8",
      "Day Sight": "140",
      "Night Sight": "80",
      "Speed": "220",
      "Build Time": "55",
      "Attack Type": "Siege",
      "Weapon Type": "Instant",
      "Ground Attack": "50",
      "Maximum Ground Attack": "68",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "13.5",
      "Maximum Air Attack": "18",
      "Cooldown": "2.1",
      "Range": "19",
      "Maximum Range": "50",
      "Race": "Human",
      "Animation": "http://classic.battle.net/war3/images/human/units/animations/siegeengine.gif",
      "Portrait": "http://classic.battle.net/war3/images/human/units/portraits/siegeengine.gif"
    },
    "Gryphon Rider": {
      "Unit": "Gryphon Rider",
      "Gold": "280",
      "Lumber": "70",
      "Supply": "4",
      "Hit Points": "825",
      "Maximum Hit Points": "975",
      "Armor Type": "Light",
      "Armor": "0",
      "Maximum Armor": "6",
      "Day Sight": "160",
      "Night Sight": "90",
      "Speed": "320",
      "Build Time": "45",
      "Attack Type": "Magic",
      "Weapon Type": "Mline",
      "Ground Attack": "50",
      "Maximum Ground Attack": "68",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "50",
      "Maximum Air Attack": "68",
      "Cooldown": "2.2/2.4",
      "Range": "45",
      "Maximum Range": "45",
      "Race": "Human",
      "Animation": "http://classic.battle.net/war3/images/human/units/animations/gryphonrider.gif",
      "Portrait": "http://classic.battle.net/war3/images/human/units/portraits/gryphon.gif"
    },
    "Dragonhawk Rider": {
      "Unit": "Dragonhawk Rider",
      "Gold": "200",
      "Lumber": "30",
      "Supply": "3",
      "Hit Points": "575",
      "Maximum Hit Points": "725",
      "Armor Type": "Light",
      "Armor": "1",
      "Maximum Armor": "7",
      "Day Sight": "140",
      "Night Sight": "80",
      "Speed": "350",
      "Build Time": "28",
      "Attack Type": "Pierce",
      "Weapon Type": "Missile",
      "Ground Attack": "19",
      "Maximum Ground Attack": "25",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "19",
      "Maximum Air Attack": "25",
      "Cooldown": "1.75",
      "Range": "30",
      "Maximum Range": "30",
      "Race": "Human",
      "Animation": "http://classic.battle.net/war3/images/human/units/animations/dragonhawk.gif",
      "Portrait": "http://classic.battle.net/war3/images/human/units/portraits/dragonhawk.gif"
    },
    "Water Elemental 1": {
      "Unit": "Water Elemental 1",
      "Gold": "None",
      "Lumber": "None",
      "Supply": "None",
      "Hit Points": "525",
      "Maximum Hit Points": "525",
      "Armor Type": "Heavy",
      "Armor": "0",
      "Maximum Armor": "0",
      "Day Sight": "120",
      "Night Sight": "80",
      "Speed": "220",
      "Build Time": "N/A",
      "Attack Type": "Pierce",
      "Weapon Type": "Missile",
      "Ground Attack": "20",
      "Maximum Ground Attack": "20",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "20",
      "Maximum Air Attack": "20",
      "Cooldown": "1.5",
      "Range": "30",
      "Maximum Range": "30",
      "Race": "Human",
      "Animation": "http://classic.battle.net/war3/images/human/units/animations/waterelement.gif",
      "Portrait": "http://classic.battle.net/war3/images/human/units/portraits/waterelement.gif"
    },
    "Water Elemental 2": {
      "Unit": "Water Elemental 2",
      "Gold": "None",
      "Lumber": "None",
      "Supply": "None",
      "Hit Points": "675",
      "Maximum Hit Points": "675",
      "Armor Type": "Heavy",
      "Armor": "1",
      "Maximum Armor": "1",
      "Day Sight": "120",
      "Night Sight": "80",
      "Speed": "220",
      "Build Time": "N/A",
      "Attack Type": "Pierce",
      "Weapon Type": "Missile",
      "Ground Attack": "35",
      "Maximum Ground Attack": "35",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "35",
      "Maximum Air Attack": "35",
      "Cooldown": "1.5",
      "Range": "30",
      "Maximum Range": "30",
      "Race": "Human",
      "Animation": "http://classic.battle.net/war3/images/human/units/animations/waterelement.gif",
      "Portrait": "http://classic.battle.net/war3/images/human/units/portraits/waterelement.gif"
    },
    "Water Elemental 3": {
      "Unit": "Water Elemental 3",
      "Gold": "None",
      "Lumber": "None",
      "Supply": "None",
      "Hit Points": "900",
      "Maximum Hit Points": "900",
      "Armor Type": "Heavy",
      "Armor": "2",
      "Maximum Armor": "2",
      "Day Sight": "120",
      "Night Sight": "80",
      "Speed": "220",
      "Build Time": "N/A",
      "Attack Type": "Pierce",
      "Weapon Type": "Missile",
      "Ground Attack": "45",
      "Maximum Ground Attack": "45",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "45",
      "Maximum Air Attack": "45",
      "Cooldown": "1.5",
      "Range": "30",
      "Maximum Range": "30",
      "Race": "Human",
      "Animation": "http://classic.battle.net/war3/images/human/units/animations/waterelement.gif",
      "Portrait": "http://classic.battle.net/war3/images/human/units/portraits/waterelement.gif"
    },
    "Phoenix": {
      "Unit": "Phoenix",
      "Gold": "None",
      "Lumber": "None",
      "Supply": "None",
      "Hit Points": "1250",
      "Maximum Hit Points": "1250",
      "Armor Type": "Light",
      "Armor": "1",
      "Maximum Armor": "1",
      "Day Sight": "160",
      "Night Sight": "80",
      "Speed": "320",
      "Build Time": "N/A",
      "Attack Type": "Magic",
      "Weapon Type": "Msplash",
      "Ground Attack": "68",
      "Maximum Ground Attack": "68",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "68",
      "Maximum Air Attack": "68",
      "Cooldown": "1.4",
      "Range": "60",
      "Maximum Range": "60",
      "Race": "Human",
      "Animation": "http://classic.battle.net/war3/images/human/units/animations/phoenix.gif",
      "Portrait": "http://classic.battle.net/war3/images/human/units/portraits/phoenix.gif"
    }
  },
  "Orc": {
    "Great Hall": {
      "Unit": "Great Hall",
      "Gold": "385",
      "Lumber": "185",
      "Build Time": "150",
      "Portrait": returnImageString('Orc', 'greathall')
    },
    "Stronghold": {
      "Unit": "Stronghold",
      "Gold": "315",
      "Lumber": "190",
      "Build Time": "140",
      "Portrait": returnImageString('Orc', 'stronghold')
    },
    "Fortress": {
      "Unit": "Fortress",
      "Gold": "325",
      "Lumber": "190",
      "Build Time": "140",
      "Portrait": returnImageString('Orc', 'fortress')
    },
    "Barracks": {
      "Unit": "Barracks",
      "Gold": "180",
      "Lumber": "50",
      "Build Time": "60",
      "Portrait": returnImageString('Orc', 'barracks')
    },
    "Altar of Storms": {
      "Unit": "Altar of Storms",
      "Gold": "180",
      "Lumber": "50",
      "Build Time": "60",
      "Portrait": returnImageString('Orc', 'altarofstorms')
    },
    "War Mill": {
      "Unit": "War Mill",
      "Gold": "205",
      "Lumber": "0",
      "Build Time": "70",
      "Portrait": returnImageString('Orc', 'warmill')
    },
    "Beastiary": {
      "Unit": "Beastiary",
      "Gold": "145",
      "Lumber": "140",
      "Build Time": "60",
      "Portrait": returnImageString('Orc', 'beastiary')
    },
    "Spirit Lodge": {
      "Unit": "Spirit Lodge",
      "Gold": "150",
      "Lumber": "150",
      "Build Time": "70",
      "Portrait": returnImageString('Orc', 'spiritlodge')
    },
    "Tauren Totem": {
      "Unit": "Tauren Totem",
      "Gold": "135",
      "Lumber": "155",
      "Build Time": "70",
      "Portrait": returnImageString('Orc', 'taurentotem')
    },
    "Voodoo Lounge": {
      "Unit": "Voodoo Lounge",
      "Gold": "130",
      "Lumber": "30",
      "Build Time": "60",
      "Portrait": returnImageString('Orc', 'voodoolounge')
    },
    "Burrow": {
      "Unit": "Burrow",
      "Gold": "160",
      "Lumber": "40",
      "Build Time": "50",
      "Portrait": returnImageString('Orc', 'burrow')
    },
    "Watch Tower": {
      "Unit": "Watch Tower",
      "Gold": "110",
      "Lumber": "80",
      "Build Time": "55",
      "Portrait": returnImageString('Orc', 'watchtower')
    },
    "Peon": {
      "Unit": "Peon",
      "Gold": "75",
      "Lumber": "0",
      "Supply": "1",
      "Hit Points": "250",
      "Maximum Hit Points": "250",
      "Armor Type": "Medium",
      "Armor": "0",
      "Maximum Armor": "0",
      "Day Sight": "80",
      "Night Sight": "60",
      "Speed": "190",
      "Build Time": "15",
      "Attack Type": "Normal",
      "Weapon Type": "Normal",
      "Ground Attack": "7.5",
      "Maximum Ground Attack": "7.5",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "None",
      "Maximum Air Attack": "None",
      "Cooldown": "3",
      "Range": "Melee",
      "Maximum Range": "Melee",
      "Race": "Orc",
      "Animation": "http://classic.battle.net/war3/images/orc/units/animations/peon.gif",
      "Portrait": "http://classic.battle.net/war3/images/orc/units/portraits/peon.gif"
    },
    "Grunt": {
      "Unit": "Grunt",
      "Gold": "200",
      "Lumber": "0",
      "Supply": "3",
      "Hit Points": "700",
      "Maximum Hit Points": "800",
      "Armor Type": "Heavy",
      "Armor": "1",
      "Maximum Armor": "7",
      "Day Sight": "140",
      "Night Sight": "80",
      "Speed": "270",
      "Build Time": "30",
      "Attack Type": "Normal",
      "Weapon Type": "Normal",
      "Ground Attack": "19.5",
      "Maximum Ground Attack": "30",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "None",
      "Maximum Air Attack": "None",
      "Cooldown": "1.6",
      "Range": "Melee",
      "Maximum Range": "Melee",
      "Race": "Orc",
      "Animation": "http://classic.battle.net/war3/images/orc/units/animations/grunt.gif",
      "Portrait": "http://classic.battle.net/war3/images/orc/units/portraits/grunt.gif"
    },
    "T. Headhunter": {
      "Unit": "T. Headhunter",
      "Gold": "135",
      "Lumber": "20",
      "Supply": "2",
      "Hit Points": "350",
      "Maximum Hit Points": "350",
      "Armor Type": "Medium",
      "Armor": "0",
      "Maximum Armor": "6",
      "Day Sight": "140",
      "Night Sight": "80",
      "Speed": "270",
      "Build Time": "20",
      "Attack Type": "Pierce",
      "Weapon Type": "Missile",
      "Ground Attack": "25",
      "Maximum Ground Attack": "34",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "25",
      "Maximum Air Attack": "34",
      "Cooldown": "2.31",
      "Range": "45",
      "Maximum Range": "45",
      "Race": "Orc",
      "Animation": "http://classic.battle.net/war3/images/orc/units/animations/headhunter.gif",
      "Portrait": "http://classic.battle.net/war3/images/orc/units/portraits/headhunter.gif"
    },
    "T. Berserker": {
      "Unit": "T. Berserker",
      "Gold": "135",
      "Lumber": "20",
      "Supply": "2",
      "Hit Points": "450",
      "Maximum Hit Points": "450",
      "Armor Type": "Medium",
      "Armor": "0",
      "Maximum Armor": "6",
      "Day Sight": "140",
      "Night Sight": "80",
      "Speed": "270",
      "Build Time": "22",
      "Attack Type": "Pierce",
      "Weapon Type": "Missile",
      "Ground Attack": "25",
      "Maximum Ground Attack": "34",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "25",
      "Maximum Air Attack": "34",
      "Cooldown": "2.31",
      "Range": "45",
      "Maximum Range": "45",
      "Race": "Orc",
      "Animation": "http://classic.battle.net/war3/images/orc/units/animations/berserker.gif",
      "Portrait": "http://classic.battle.net/war3/images/orc/units/portraits/berserker.gif"
    },
    "Demolisher": {
      "Unit": "Demolisher",
      "Gold": "220",
      "Lumber": "50",
      "Supply": "4",
      "Hit Points": "425",
      "Maximum Hit Points": "425",
      "Armor Type": "Heavy",
      "Armor": "2",
      "Maximum Armor": "6",
      "Day Sight": "140",
      "Night Sight": "120",
      "Speed": "220",
      "Build Time": "40",
      "Attack Type": "Siege",
      "Weapon Type": "Artillery",
      "Ground Attack": "80.5",
      "Maximum Ground Attack": "109",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "None",
      "Maximum Air Attack": "None",
      "Cooldown": "4.5",
      "Range": "25",
      "Maximum Range": "115",
      "Race": "Orc",
      "Animation": "http://classic.battle.net/war3/images/orc/units/animations/demolisher.gif",
      "Portrait": "http://classic.battle.net/war3/images/orc/units/portraits/demolisher.gif"
    },
    "Raider": {
      "Unit": "Raider",
      "Gold": "180",
      "Lumber": "40",
      "Supply": "3",
      "Hit Points": "610",
      "Maximum Hit Points": "425",
      "Armor Type": "Medium",
      "Armor": "1",
      "Maximum Armor": "7",
      "Day Sight": "140",
      "Night Sight": "80",
      "Speed": "350",
      "Build Time": "28",
      "Attack Type": "Siege",
      "Weapon Type": "Normal",
      "Ground Attack": "25",
      "Maximum Ground Attack": "34",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "None",
      "Maximum Air Attack": "None",
      "Cooldown": "1.85",
      "Range": "Melee",
      "Maximum Range": "Melee",
      "Race": "Orc",
      "Animation": "http://classic.battle.net/war3/images/orc/units/animations/wolfrider.gif",
      "Portrait": "http://classic.battle.net/war3/images/orc/units/portraits/wolfrider.gif"
    },
    "Tauren": {
      "Unit": "Tauren",
      "Gold": "280",
      "Lumber": "80",
      "Supply": "5",
      "Hit Points": "1300",
      "Maximum Hit Points": "1300",
      "Armor Type": "Heavy",
      "Armor": "3",
      "Maximum Armor": "9",
      "Day Sight": "140",
      "Night Sight": "80",
      "Speed": "270",
      "Build Time": "44",
      "Attack Type": "Normal",
      "Weapon Type": "Normal",
      "Ground Attack": "33",
      "Maximum Ground Attack": "45",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "None",
      "Maximum Air Attack": "None",
      "Cooldown": "1.9",
      "Range": "Melee",
      "Maximum Range": "Melee",
      "Race": "Orc",
      "Animation": "http://classic.battle.net/war3/images/orc/units/animations/tauren.gif",
      "Portrait": "http://classic.battle.net/war3/images/orc/units/portraits/tauren.gif"
    },
    "Shaman": {
      "Unit": "Shaman",
      "Gold": "130",
      "Lumber": "20",
      "Supply": "2",
      "Hit Points": "335",
      "Maximum Hit Points": "415",
      "Armor Type": "Unarmored",
      "Armor": "0",
      "Maximum Armor": "0",
      "Day Sight": "140",
      "Night Sight": "80",
      "Speed": "270",
      "Build Time": "30",
      "Attack Type": "Magic",
      "Weapon Type": "Missile",
      "Ground Attack": "8.5",
      "Maximum Ground Attack": "8.5",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "8.5",
      "Maximum Air Attack": "8.5",
      "Cooldown": "2.1",
      "Range": "60",
      "Maximum Range": "60",
      "Race": "Orc",
      "Animation": "http://classic.battle.net/war3/images/orc/units/animations/shaman.gif",
      "Portrait": "http://classic.battle.net/war3/images/orc/units/portraits/shaman.gif"
    },
    "Witch Doctor": {
      "Unit": "Witch Doctor",
      "Gold": "145",
      "Lumber": "25",
      "Supply": "2",
      "Hit Points": "315",
      "Maximum Hit Points": "395",
      "Armor Type": "Unarmored",
      "Armor": "0",
      "Maximum Armor": "0",
      "Day Sight": "140",
      "Night Sight": "80",
      "Speed": "270",
      "Build Time": "30",
      "Attack Type": "Magic",
      "Weapon Type": "Missile",
      "Ground Attack": "12",
      "Maximum Ground Attack": "12",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "12",
      "Maximum Air Attack": "12",
      "Cooldown": "1.75",
      "Range": "60",
      "Maximum Range": "60",
      "Race": "Orc",
      "Animation": "http://classic.battle.net/war3/images/orc/units/animations/witchdoctor.gif",
      "Portrait": "http://classic.battle.net/war3/images/orc/units/portraits/witchdoctor.gif"
    },
    "Spirit Walker": {
      "Unit": "Spirit Walker",
      "Gold": "195",
      "Lumber": "35",
      "Supply": "3",
      "Hit Points": "500",
      "Maximum Hit Points": "620",
      "Armor Type": "Unarmored",
      "Armor": "0",
      "Maximum Armor": "0",
      "Day Sight": "140",
      "Night Sight": "80",
      "Speed": "270",
      "Build Time": "38",
      "Attack Type": "Magic",
      "Weapon Type": "Missile",
      "Ground Attack": "19.5",
      "Maximum Ground Attack": "19.5",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "19.5",
      "Maximum Air Attack": "19.5",
      "Cooldown": "1.75",
      "Range": "40",
      "Maximum Range": "40",
      "Race": "Orc",
      "Animation": "http://classic.battle.net/war3/images/orc/units/animations/spiritwalker.gif",
      "Portrait": "http://classic.battle.net/war3/images/orc/units/portraits/spiritwalker.gif"
    },
    "Kodo Beast": {
      "Unit": "Kodo Beast",
      "Gold": "255",
      "Lumber": "60",
      "Supply": "4",
      "Hit Points": "1000",
      "Maximum Hit Points": "1000",
      "Armor Type": "Unarmored",
      "Armor": "1",
      "Maximum Armor": "1",
      "Day Sight": "140",
      "Night Sight": "80",
      "Speed": "220",
      "Build Time": "30",
      "Attack Type": "Pierce",
      "Weapon Type": "Missile",
      "Ground Attack": "18",
      "Maximum Ground Attack": "18",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "18",
      "Maximum Air Attack": "18",
      "Cooldown": "1.44",
      "Range": "50",
      "Maximum Range": "50",
      "Race": "Orc",
      "Animation": "http://classic.battle.net/war3/images/orc/units/animations/kodo.gif",
      "Portrait": "http://classic.battle.net/war3/images/orc/units/portraits/kodobeast.gif"
    },
    "Wind Rider": {
      "Unit": "Wind Rider",
      "Gold": "265",
      "Lumber": "40",
      "Supply": "4",
      "Hit Points": "570",
      "Maximum Hit Points": "570",
      "Armor Type": "Light",
      "Armor": "0",
      "Maximum Armor": "6",
      "Day Sight": "160",
      "Night Sight": "80",
      "Speed": "320",
      "Build Time": "35",
      "Attack Type": "Pierce",
      "Weapon Type": "Missile",
      "Ground Attack": "40",
      "Maximum Ground Attack": "49",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "40",
      "Maximum Air Attack": "49",
      "Cooldown": "2",
      "Range": "45",
      "Maximum Range": "45",
      "Race": "Orc",
      "Animation": "http://classic.battle.net/war3/images/orc/units/animations/wyvernrider.gif",
      "Portrait": "http://classic.battle.net/war3/images/orc/units/portraits/wyvernrider.gif"
    },
    "Troll Batrider": {
      "Unit": "Troll Batrider",
      "Gold": "160",
      "Lumber": "40",
      "Supply": "2",
      "Hit Points": "325",
      "Maximum Hit Points": "325",
      "Armor Type": "Light",
      "Armor": "0",
      "Maximum Armor": "6",
      "Day Sight": "140",
      "Night Sight": "140",
      "Speed": "320",
      "Build Time": "28",
      "Attack Type": "Siege",
      "Weapon Type": "Missile",
      "Ground Attack": "14",
      "Maximum Ground Attack": "20",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "None",
      "Maximum Air Attack": "None",
      "Cooldown": "1.8",
      "Range": "30",
      "Maximum Range": "30",
      "Race": "Orc",
      "Animation": "http://classic.battle.net/war3/images/orc/units/animations/batrider.gif",
      "Portrait": "http://classic.battle.net/war3/images/orc/units/portraits/batrider.gif"
    },
    "Spirit Wolf": {
      "Unit": "Spirit Wolf",
      "Gold": "None",
      "Lumber": "None",
      "Supply": "None",
      "Hit Points": "200",
      "Maximum Hit Points": "200",
      "Armor Type": "Heavy",
      "Armor": "0",
      "Maximum Armor": "0",
      "Day Sight": "120",
      "Night Sight": "80",
      "Speed": "320",
      "Build Time": "None",
      "Attack Type": "Normal",
      "Weapon Type": "Normal",
      "Ground Attack": "11.5",
      "Maximum Ground Attack": "11.5",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "None",
      "Maximum Air Attack": "None",
      "Cooldown": "1",
      "Range": "Melee",
      "Maximum Range": "Melee",
      "Race": "Orc",
      "Animation": "http://classic.battle.net/war3/images/orc/units/animations/spiritwolf.gif",
      "Portrait": "http://classic.battle.net/war3/images/orc/units/portraits/direwolf.gif"
    },
    "Dire Wolf": {
      "Unit": "Dire Wolf",
      "Gold": "None",
      "Lumber": "None",
      "Supply": "None",
      "Hit Points": "300",
      "Maximum Hit Points": "300",
      "Armor Type": "Heavy",
      "Armor": "0",
      "Maximum Armor": "0",
      "Day Sight": "120",
      "Night Sight": "80",
      "Speed": "350",
      "Build Time": "None",
      "Attack Type": "Normal",
      "Weapon Type": "Normal",
      "Ground Attack": "16.5",
      "Maximum Ground Attack": "16.5",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "None",
      "Maximum Air Attack": "None",
      "Cooldown": "1",
      "Range": "Melee",
      "Maximum Range": "Melee",
      "Race": "Orc",
      "Animation": "http://classic.battle.net/war3/images/orc/units/animations/direwolf.gif",
      "Portrait": "http://classic.battle.net/war3/images/orc/units/portraits/direwolf.gif"
    },
    "Shadow Wolf": {
      "Unit": "Shadow Wolf",
      "Gold": "None",
      "Lumber": "None",
      "Supply": "None",
      "Hit Points": "500",
      "Maximum Hit Points": "500",
      "Armor Type": "Heavy",
      "Armor": "0",
      "Maximum Armor": "0",
      "Day Sight": "120",
      "Night Sight": "80",
      "Speed": "350",
      "Build Time": "None",
      "Attack Type": "Normal",
      "Weapon Type": "Normal",
      "Ground Attack": "21.5",
      "Maximum Ground Attack": "21.5",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "None",
      "Maximum Air Attack": "None",
      "Cooldown": "1",
      "Range": "Melee",
      "Maximum Range": "Melee",
      "Race": "Orc",
      "Animation": "http://classic.battle.net/war3/images/orc/units/animations/shadowwolf.gif",
      "Portrait": "http://classic.battle.net/war3/images/orc/units/portraits/direwolf.gif"
    },
    "Serpent Ward Level 1": {
      "Unit": "Serpent Ward Level 1",
      "Gold": "None",
      "Lumber": "None",
      "Supply": "None",
      "Hit Points": "75",
      "Maximum Hit Points": "135",
      "Armor Type": "Heavy",
      "Armor": "0",
      "Maximum Armor": "0",
      "Day Sight": "120",
      "Night Sight": "80",
      "Speed": "None",
      "Build Time": "None",
      "Attack Type": "Pierce",
      "Weapon Type": "Missile",
      "Ground Attack": "12",
      "Maximum Ground Attack": "12",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "12",
      "Maximum Air Attack": "12",
      "Cooldown": "1.5",
      "Range": "60",
      "Maximum Range": "60",
      "Race": "Orc",
      "Animation": "http://classic.battle.net/war3/images/orc/units/animations/serpentward.gif",
      "Portrait": "http://classic.battle.net/war3/images/orc/units/portraits/serpentward.gif"
    },
    "Serpent Ward Level 2": {
      "Unit": "Serpent Ward Level 2",
      "Gold": "None",
      "Lumber": "None",
      "Supply": "None",
      "Hit Points": "75",
      "Maximum Hit Points": "135",
      "Armor Type": "Heavy",
      "Armor": "0",
      "Maximum Armor": "0",
      "Day Sight": "120",
      "Night Sight": "80",
      "Speed": "None",
      "Build Time": "None",
      "Attack Type": "Pierce",
      "Weapon Type": "Missile",
      "Ground Attack": "24.5",
      "Maximum Ground Attack": "24.5",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "24.5",
      "Maximum Air Attack": "24.5",
      "Cooldown": "1.5",
      "Range": "60",
      "Maximum Range": "60",
      "Race": "Orc",
      "Animation": "http://classic.battle.net/war3/images/orc/units/animations/serpentward.gif",
      "Portrait": "http://classic.battle.net/war3/images/orc/units/portraits/serpentward.gif"
    },
    "Serpent Ward Level 3": {
      "Unit": "Serpent Ward Level 3",
      "Gold": "None",
      "Lumber": "None",
      "Supply": "None",
      "Hit Points": "75",
      "Maximum Hit Points": "135",
      "Armor Type": "Heavy",
      "Armor": "0",
      "Maximum Armor": "0",
      "Day Sight": "120",
      "Night Sight": "80",
      "Speed": "None",
      "Build Time": "None",
      "Attack Type": "Pierce",
      "Weapon Type": "Missile",
      "Ground Attack": "43",
      "Maximum Ground Attack": "43",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "43",
      "Maximum Air Attack": "43",
      "Cooldown": "1.5",
      "Range": "60",
      "Maximum Range": "60",
      "Race": "Orc",
      "Animation": "http://classic.battle.net/war3/images/orc/units/animations/serpentward.gif",
      "Portrait": "http://classic.battle.net/war3/images/orc/units/portraits/serpentward.gif"
    }
  },
  "Undead": {
    "Necropolis": {
      "Unit": "Necropolis",
      "Gold": "255",
      "Lumber": "220",
      "Build Time": "100",
      "Portrait": returnImageString('Undead', 'necropolis')
    },
    "Halls of the dead": {
      "Unit": "Halls of the Dead",
      "Gold": "320",
      "Lumber": "210",
      "Build Time": "100",
      "Portrait": returnImageString('Undead', 'hallsofthedead')
    },
    "Black Citadel": {
      "Unit": "Black Citadel",
      "Gold": "325",
      "Lumber": "230",
      "Build Time": "140",
      "Portrait": returnImageString('Undead', 'blackcitadel')
    },
    "Crypt": {
      "Unit": "Crypt",
      "Gold": "200",
      "Lumber": "50",
      "Build Time": "140",
      "Portrait": returnImageString('Undead', 'crypt')
    },
    "Ziggurat": {
      "Unit": "Ziggurat",
      "Gold": "150",
      "Lumber": "50",
      "Build Time": "50",
      "Portrait": returnImageString('Undead', 'ziggurat')
    },
    "Altar of Darkness": {
      "Unit": "Altar of Darkness",
      "Gold": "180",
      "Lumber": "50",
      "Build Time": "60",
      "Portrait": returnImageString('Undead', 'altarofdarkness')
    },
    "Graveyard": {
      "Unit": "Graveyard",
      "Gold": "215",
      "Lumber": "0",
      "Build Time": "60",
      "Portrait": returnImageString('Undead', 'graveyard')
    },
    "Slaughterhouse": {
      "Unit": "Slaughterhouse",
      "Gold": "140",
      "Lumber": "135",
      "Build Time": "60",
      "Portrait": returnImageString('Undead', 'slaughterhouse')
    },
    "Temple of the Damned": {
      "Unit": "Temple of the Damned",
      "Gold": "155",
      "Lumber": "140",
      "Build Time": "60",
      "Portrait": returnImageString('Undead', 'templeofthedamned')
    },
    "Sacrificial Pit": {
      "Unit": "Sacrificial Pit",
      "Gold": "75",
      "Lumber": "150",
      "Build Time": "45",
      "Portrait": returnImageString('Undead', 'sacrificialpit')
    },
    "Boneyard": {
      "Unit": "Boneyard",
      "Gold": "175",
      "Lumber": "200",
      "Build Time": "70",
      "Portrait": returnImageString('Undead', 'boneyard')
    },
    "Tomb of Relics": {
      "Unit": "Tomb of Relics",
      "Gold": "130",
      "Lumber": "30",
      "Build Time": "60"
    },
    "Acolyte": {
      "Unit": "Acolyte",
      "Gold": "75",
      "Lumber": "0",
      "Supply": "1",
      "Hit Points": "220",
      "Maximum Hit Points": "220",
      "Armor Type": "Medium",
      "Armor": "0",
      "Maximum Armor": "0",
      "Day Sight": "80",
      "Night Sight": "60",
      "Speed": "220",
      "Build Time": "15",
      "Attack Type": "Normal",
      "Weapon Type": "Normal",
      "Ground Attack": "9.5",
      "Maximum Ground Attack": "9.5",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "None",
      "Maximum Air Attack": "None",
      "Cooldown": "2.5",
      "Range": "Melee",
      "Maximum Range": "Melee",
      "Race": "Undead",
      "Animation": "http://classic.battle.net/war3/images/undead/units/animations/acolyte.gif",
      "Portrait": "http://classic.battle.net/war3/images/undead/units/portraits/acolyte.gif"
    },
    "Ghoul": {
      "Unit": "Ghoul",
      "Gold": "120",
      "Lumber": "0",
      "Supply": "2",
      "Hit Points": "340",
      "Maximum Hit Points": "340",
      "Armor Type": "Heavy",
      "Armor": "0",
      "Maximum Armor": "6",
      "Day Sight": "140",
      "Night Sight": "80",
      "Speed": "270/350",
      "Build Time": "18",
      "Attack Type": "Normal",
      "Weapon Type": "Normal",
      "Ground Attack": "13",
      "Maximum Ground Attack": "17.5",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "None",
      "Maximum Air Attack": "None",
      "Cooldown": "1.3/1.04",
      "Range": "Melee",
      "Maximum Range": "Melee",
      "Race": "Undead",
      "Animation": "http://classic.battle.net/war3/images/undead/units/animations/ghoul.gif",
      "Portrait": "http://classic.battle.net/war3/images/undead/units/portraits/ghoul.gif"
    },
    "Crypt Fiend": {
      "Unit": "Crypt Fiend",
      "Gold": "215",
      "Lumber": "40",
      "Supply": "3",
      "Hit Points": "550",
      "Maximum Hit Points": "550",
      "Armor Type": "Medium",
      "Armor": "0",
      "Maximum Armor": "6",
      "Day Sight": "140",
      "Night Sight": "80",
      "Speed": "270",
      "Build Time": "30",
      "Attack Type": "Pierce",
      "Weapon Type": "Missile",
      "Ground Attack": "28.5",
      "Maximum Ground Attack": "39",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "None",
      "Maximum Air Attack": "None",
      "Cooldown": "2",
      "Range": "55",
      "Maximum Range": "55",
      "Race": "Undead",
      "Animation": "http://classic.battle.net/war3/images/undead/units/animations/cryptfiend.gif",
      "Portrait": "http://classic.battle.net/war3/images/undead/units/portraits/cryptfiend.gif"
    },
    "Gargoyle": {
      "Unit": "Gargoyle",
      "Gold": "185",
      "Lumber": "30",
      "Supply": "2",
      "Hit Points": "410",
      "Maximum Hit Points": "410",
      "Armor Type": "Unarmored",
      "Armor": "3",
      "Maximum Armor": "9",
      "Day Sight": "160",
      "Night Sight": "80",
      "Speed": "350",
      "Build Time": "35",
      "Attack Type": "Pierce/Normal",
      "Weapon Type": "Missile/Normal",
      "Ground Attack": "19.5",
      "Maximum Ground Attack": "27",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "65.5",
      "Maximum Air Attack": "82",
      "Cooldown": "2.2/1.4",
      "Range": "30",
      "Maximum Range": "Melee",
      "Race": "Undead",
      "Animation": "http://classic.battle.net/war3/images/undead/units/animations/gargoyle.gif",
      "Portrait": "http://classic.battle.net/war3/images/undead/units/portraits/gargoyle.gif"
    },
    "Abomination": {
      "Unit": "Abomination",
      "Gold": "240",
      "Lumber": "70",
      "Supply": "4",
      "Hit Points": "1175",
      "Maximum Hit Points": "1175",
      "Armor Type": "Heavy",
      "Armor": "2",
      "Maximum Armor": "8",
      "Day Sight": "140",
      "Night Sight": "80",
      "Speed": "270",
      "Build Time": "40",
      "Attack Type": "Normal",
      "Weapon Type": "Normal",
      "Ground Attack": "36",
      "Maximum Ground Attack": "48",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "None",
      "Maximum Air Attack": "None",
      "Cooldown": "1.9",
      "Range": "Melee",
      "Maximum Range": "Melee",
      "Race": "Undead",
      "Animation": "http://classic.battle.net/war3/images/undead/units/animations/abomination.gif",
      "Portrait": "http://classic.battle.net/war3/images/undead/units/portraits/abomination.gif"
    },
    "Meat Wagon": {
      "Unit": "Meat Wagon",
      "Gold": "230",
      "Lumber": "50",
      "Supply": "4",
      "Hit Points": "380",
      "Maximum Hit Points": "380",
      "Armor Type": "Heavy",
      "Armor": "2",
      "Maximum Armor": "2",
      "Day Sight": "140",
      "Night Sight": "120",
      "Speed": "220",
      "Build Time": "45",
      "Attack Type": "Siege",
      "Weapon Type": "Artillery",
      "Ground Attack": "79.5",
      "Maximum Ground Attack": "108",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "None",
      "Maximum Air Attack": "None",
      "Cooldown": "4",
      "Range": "25",
      "Maximum Range": "115",
      "Race": "Undead",
      "Animation": "http://classic.battle.net/war3/images/undead/units/animations/meatwagon.gif",
      "Portrait": "http://classic.battle.net/war3/images/undead/units/portraits/meatwagon.gif"
    },
    "Necromancer": {
      "Unit": "Necromancer",
      "Gold": "145",
      "Lumber": "20",
      "Supply": "2",
      "Hit Points": "305",
      "Maximum Hit Points": "385",
      "Armor Type": "Unarmored",
      "Armor": "0",
      "Maximum Armor": "0",
      "Day Sight": "140",
      "Night Sight": "90",
      "Speed": "270",
      "Build Time": "24",
      "Attack Type": "Magic",
      "Weapon Type": "Missile",
      "Ground Attack": "8.5",
      "Maximum Ground Attack": "8.5",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "8.5",
      "Maximum Air Attack": "8.5",
      "Cooldown": "1.8",
      "Range": "60",
      "Maximum Range": "60",
      "Race": "Undead",
      "Animation": "http://classic.battle.net/war3/images/undead/units/animations/necromancer.gif",
      "Portrait": "http://classic.battle.net/war3/images/undead/units/portraits/necromancer.gif"
    },
    "Banshee": {
      "Unit": "Banshee",
      "Gold": "155",
      "Lumber": "30",
      "Supply": "2",
      "Hit Points": "285",
      "Maximum Hit Points": "365",
      "Armor Type": "Unarmored",
      "Armor": "0",
      "Maximum Armor": "0",
      "Day Sight": "140",
      "Night Sight": "80",
      "Speed": "270",
      "Build Time": "28",
      "Attack Type": "Magic",
      "Weapon Type": "Missile",
      "Ground Attack": "11",
      "Maximum Ground Attack": "11",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "11",
      "Maximum Air Attack": "11",
      "Cooldown": "1.5",
      "Range": "60",
      "Maximum Range": "60",
      "Race": "Undead",
      "Animation": "http://classic.battle.net/war3/images/undead/units/animations/banshee.gif",
      "Portrait": "http://classic.battle.net/war3/images/undead/units/portraits/banshee.gif"
    },
    "Frost Wyrm": {
      "Unit": "Frost Wyrm",
      "Gold": "385",
      "Lumber": "120",
      "Supply": "7",
      "Hit Points": "1350",
      "Maximum Hit Points": "1350",
      "Armor Type": "Light",
      "Armor": "1",
      "Maximum Armor": "7",
      "Day Sight": "160",
      "Night Sight": "80",
      "Speed": "270",
      "Build Time": "65",
      "Attack Type": "Magic",
      "Weapon Type": "Msplash",
      "Ground Attack": "104",
      "Maximum Ground Attack": "123.5",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "89",
      "Maximum Air Attack": "107",
      "Cooldown": "3",
      "Range": "30",
      "Maximum Range": "30",
      "Race": "Undead",
      "Animation": "http://classic.battle.net/war3/images/undead/units/animations/frostwyrm.gif",
      "Portrait": "http://classic.battle.net/war3/images/undead/units/portraits/frostwyrm.gif"
    },
    "Shade": {
      "Unit": "Shade",
      "Gold": "N/A",
      "Lumber": "N/A",
      "Supply": "1",
      "Hit Points": "125",
      "Maximum Hit Points": "125",
      "Armor Type": "Medium",
      "Armor": "0",
      "Maximum Armor": "0",
      "Day Sight": "190",
      "Night Sight": "80",
      "Speed": "350",
      "Build Time": "15",
      "Attack Type": "N/A",
      "Weapon Type": "N/A",
      "Ground Attack": "N/A",
      "Maximum Ground Attack": "N/A",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "N/A",
      "Maximum Air Attack": "N/A",
      "Cooldown": "N/A",
      "Range": "N/A",
      "Maximum Range": "N/A",
      "Race": "Undead",
      "Animation": "http://classic.battle.net/war3/images/undead/units/animations/shade.gif",
      "Portrait": "http://classic.battle.net/war3/images/undead/units/portraits/shade.gif"
    },
    "Skeleton Warrior": {
      "Unit": "Skeleton Warrior",
      "Gold": "N/A",
      "Lumber": "N/A",
      "Supply": "0",
      "Hit Points": "180",
      "Maximum Hit Points": "180",
      "Armor Type": "Heavy",
      "Armor": "1",
      "Maximum Armor": "7",
      "Day Sight": "80",
      "Night Sight": "60",
      "Speed": "270",
      "Build Time": "N/A",
      "Attack Type": "Normal",
      "Weapon Type": "Normal",
      "Ground Attack": "14.5",
      "Maximum Ground Attack": "19",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "None",
      "Maximum Air Attack": "None",
      "Cooldown": "2",
      "Range": "Melee",
      "Maximum Range": "Melee",
      "Race": "Undead",
      "Animation": "http://classic.battle.net/war3/images/undead/units/animations/skeleton.gif",
      "Portrait": "http://classic.battle.net/war3/images/undead/units/portraits/skeleton.gif"
    },
    "Skeletal Mage": {
      "Unit": "Skeletal Mage",
      "Gold": "N/A",
      "Lumber": "N/A",
      "Supply": "0",
      "Hit Points": "230",
      "Maximum Hit Points": "230",
      "Armor Type": "Medium",
      "Armor": "0",
      "Maximum Armor": "6",
      "Day Sight": "140",
      "Night Sight": "90",
      "Speed": "270",
      "Build Time": "N/A",
      "Attack Type": "Pierce",
      "Weapon Type": "Missile",
      "Ground Attack": "11.5",
      "Maximum Ground Attack": "16",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "11.5",
      "Maximum Air Attack": "16",
      "Cooldown": "1.5",
      "Range": "50",
      "Maximum Range": "50",
      "Race": "Undead",
      "Animation": "http://classic.battle.net/war3/images/undead/units/animations/skeletalmage.gif",
      "Portrait": "http://classic.battle.net/war3/images/undead/units/portraits/skeletalmage.gif"
    },
    "Infernal": {
      "Unit": "Infernal",
      "Gold": "N/A",
      "Lumber": "N/A",
      "Supply": "N/A",
      "Hit Points": "1500",
      "Maximum Hit Points": "1500",
      "Armor Type": "Heavy",
      "Armor": "6",
      "Maximum Armor": "6",
      "Day Sight": "140",
      "Night Sight": "80",
      "Speed": "320",
      "Build Time": "N/A",
      "Attack Type": "Chaos",
      "Weapon Type": "Normal",
      "Ground Attack": "54.5",
      "Maximum Ground Attack": "54.5",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "None",
      "Maximum Air Attack": "None",
      "Cooldown": "1.35",
      "Range": "Melee",
      "Maximum Range": "Melee",
      "Race": "Undead",
      "Animation": "http://classic.battle.net/war3/images/undead/units/animations/infernal.gif",
      "Portrait": "http://classic.battle.net/war3/images/undead/units/portraits/infernal.gif"
    },
    "Carrion Beetle 1": {
      "Unit": "Carrion Beetle 1",
      "Gold": "N/A",
      "Lumber": "N/A",
      "Supply": "0",
      "Hit Points": "140",
      "Maximum Hit Points": "140",
      "Armor Type": "Heavy",
      "Armor": "2",
      "Maximum Armor": "2",
      "Day Sight": "120",
      "Night Sight": "80",
      "Speed": "270",
      "Build Time": "N/A",
      "Attack Type": "Normal",
      "Weapon Type": "Normal",
      "Ground Attack": "8.5",
      "Maximum Ground Attack": "8.5",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "None",
      "Maximum Air Attack": "None",
      "Cooldown": "1.5",
      "Range": "Melee",
      "Maximum Range": "Melee",
      "Race": "Undead",
      "Animation": "http://classic.battle.net/war3/images/undead/units/animations/scarab.gif",
      "Portrait": "http://classic.battle.net/war3/images/undead/units/portraits/scarab.gif"
    },
    "Carrion Beetle 2": {
      "Unit": "Carrion Beetle 2",
      "Gold": "N/A",
      "Lumber": "N/A",
      "Supply": "0",
      "Hit Points": "275",
      "Maximum Hit Points": "275",
      "Armor Type": "Heavy",
      "Armor": "2",
      "Maximum Armor": "2",
      "Day Sight": "120",
      "Night Sight": "80",
      "Speed": "270",
      "Build Time": "N/A",
      "Attack Type": "Normal",
      "Weapon Type": "Normal",
      "Ground Attack": "16.5",
      "Maximum Ground Attack": "16.5",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "None",
      "Maximum Air Attack": "None",
      "Cooldown": "1.5",
      "Range": "Melee",
      "Maximum Range": "Melee",
      "Race": "Undead",
      "Animation": "http://classic.battle.net/war3/images/undead/units/animations/scarab.gif",
      "Portrait": "http://classic.battle.net/war3/images/undead/units/portraits/scarab.gif"
    },
    "Carrion Beetle 3": {
      "Unit": "Carrion Beetle 3",
      "Gold": "N/A",
      "Lumber": "N/A",
      "Supply": "0",
      "Hit Points": "410",
      "Maximum Hit Points": "410",
      "Armor Type": "Heavy",
      "Armor": "2",
      "Maximum Armor": "2",
      "Day Sight": "120",
      "Night Sight": "80",
      "Speed": "270",
      "Build Time": "N/A",
      "Attack Type": "Normal",
      "Weapon Type": "Normal",
      "Ground Attack": "24.5",
      "Maximum Ground Attack": "24.5",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "None",
      "Maximum Air Attack": "None",
      "Cooldown": "1.5",
      "Range": "Melee",
      "Maximum Range": "Melee",
      "Race": "Undead",
      "Animation": "http://classic.battle.net/war3/images/undead/units/animations/scarab.gif",
      "Portrait": "http://classic.battle.net/war3/images/undead/units/portraits/scarab.gif"
    },
    "Obsidian Statue": {
      "Unit": "Obsidian Statue",
      "Gold": "200",
      "Lumber": "35",
      "Supply": "3",
      "Hit Points": "550",
      "Maximum Hit Points": "550",
      "Armor Type": "Heavy",
      "Armor": "4",
      "Maximum Armor": "4",
      "Day Sight": "120",
      "Night Sight": "80",
      "Speed": "270",
      "Build Time": "45",
      "Attack Type": "Magic",
      "Weapon Type": "Missile",
      "Ground Attack": "7.5",
      "Maximum Ground Attack": "7.5",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "7.5",
      "Maximum Air Attack": "7.5",
      "Cooldown": "2.1",
      "Range": "57.5",
      "Maximum Range": "57.5",
      "Race": "Undead",
      "Animation": "http://classic.battle.net/war3/images/undead/units/animations/obsidianstatue.gif",
      "Portrait": "http://classic.battle.net/war3/images/undead/units/portraits/obsidianstatue.gif"
    },
    "Destroyer": {
      "Unit": "Destroyer",
      "Gold": "N/A",
      "Lumber": "N/A",
      "Supply": "5",
      "Hit Points": "900",
      "Maximum Hit Points": "900",
      "Armor Type": "Light",
      "Armor": "3",
      "Maximum Armor": "9",
      "Day Sight": "140",
      "Night Sight": "100",
      "Speed": "320",
      "Build Time": "N/A",
      "Attack Type": "Magic",
      "Weapon Type": "Msplash",
      "Ground Attack": "20",
      "Maximum Ground Attack": "26",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "20",
      "Maximum Air Attack": "26",
      "Cooldown": "1.35",
      "Range": "45",
      "Maximum Range": "45",
      "Race": "Undead",
      "Animation": "http://classic.battle.net/war3/images/undead/units/animations/destroyer.gif",
      "Portrait": "http://classic.battle.net/war3/images/undead/units/portraits/destroyer.gif"
    }
  },
  "Night Elf": {
    "Tree of Life": {
      "Unit": "Tree of life",
      "Gold": "340",
      "Lumber": "185",
      "Build Time": "120",
      "Portrait": returnImageString('Night Elf', 'treeoflife')
    },
    "Tree of Ages": {
      "Unit": "Tree of Ages",
      "Gold": "320",
      "Lumber": "180",
      "Build Time": "140",
      "Portrait": returnImageString('Night Elf', 'treeofages')
    },
    "Tree of Eternity": {
      "Unit": "Tree of Eternity",
      "Gold": "330",
      "Lumber": "200",
      "Build Time": "140",
      "Portrait": returnImageString('Night Elf', 'treeofeternity')
    },
    "Ancient of War": {
      "Unit": "Ancient Of War",
      "Gold": "150",
      "Lumber": "60",
      "Build Time": "60",
      "Portrait": returnImageString('Night Elf', 'ancientofwar')
    },
    "Ancient of Lore": {
      "Unit": "Ancient of Lore",
      "Gold": "155",
      "Lumber": "145",
      "Build Time": "70",
      "Portrait": returnImageString('Night Elf', 'ancientoflore')
    },
    "Ancient of Wind": {
      "Unit": "Ancient of Wind",
      "Gold": "150",
      "Lumber": "140",
      "Build Time": "60",
      "Portrait": returnImageString('Night Elf', 'ancientofwind')
    },
    "Ancient of Wonders": {
      "Unit": "Ancient of Wonders",
      "Gold": "90",
      "Lumber": "30",
      "Build Time": "60",
      // "Portrait": returnImageString('Night Elf', 'ancientofwar')
    },
    "Moon Well": {
      "Unit": "Moon Well",
      "Gold": "180",
      "Lumber": "40",
      "Build Time": "50",
      "Portrait": returnImageString('Night Elf', 'moonwell')
    },
    "Altar of Elders": {
      "Unit": "Altar of Elders",
      "Gold": "180",
      "Lumber": "155",
      "Build Time": "60",
      "Portrait": returnImageString('Night Elf', 'altarofelders')
    },
    "Hunters Hall": {
      "Unit": "Hunters Hall",
      "Gold": "180",
      "Lumber": "100",
      "Build Time": "60",
      "Portrait": returnImageString('Night Elf', 'huntershall')
    },
    "Chimaera Roost": {
      "Unit": "Chimaera Roost",
      "Gold": "140",
      "Lumber": "190",
      "Build Time": "80",
      "Portrait": returnImageString('Night Elf', 'chimaeraroost')
    },
    "Watch Tower": {
      "Unit": "Watch Tower",
      "Gold": "110",
      "Lumber": "80",
      "Build Time": "55",
      "Portrait": returnImageString('Night Elf', 'watchtower')
    },
    "Wisp": {
      "Unit": "Wisp",
      "Gold": "60",
      "Lumber": "0",
      "Supply": "1",
      "Hit Points": "120",
      "Maximum Hit Points": "120",
      "Armor Type": "Medium",
      "Armor": "0",
      "Maximum Armor": "0",
      "Day Sight": "100",
      "Night Sight": "75",
      "Speed": "270",
      "Build Time": "14",
      "Attack Type": "None",
      "Weapon Type": "None",
      "Ground Attack": "None",
      "Maximum Ground Attack": "None",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "None",
      "Maximum Air Attack": "None",
      "Cooldown": "None",
      "Range": "None",
      "Maximum Range": "None",
      "Race": "Night Elf",
      "Animation": "http://classic.battle.net/war3/images/nightelf/units/animations/wisp.gif",
      "Portrait": "http://classic.battle.net/war3/images/nightelf/units/portraits/wisp.gif"
    },
    "Archer": {
      "Unit": "Archer",
      "Gold": "130",
      "Lumber": "10",
      "Supply": "2",
      "Hit Points": "245",
      "Maximum Hit Points": "245",
      "Armor Type": "Medium",
      "Armor": "0",
      "Maximum Armor": "6",
      "Day Sight": "140",
      "Night Sight": "80",
      "Speed": "270",
      "Build Time": "20",
      "Attack Type": "Pierce",
      "Weapon Type": "Missile",
      "Ground Attack": "17",
      "Maximum Ground Attack": "26",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "17",
      "Maximum Air Attack": "26",
      "Cooldown": "1.5",
      "Range": "50",
      "Maximum Range": "70",
      "Race": "Night Elf",
      "Animation": "http://classic.battle.net/war3/images/nightelf/units/animations/archer.gif",
      "Portrait": "http://classic.battle.net/war3/images/nightelf/units/portraits/archer.gif"
    },
    "Huntress": {
      "Unit": "Huntress",
      "Gold": "195",
      "Lumber": "20",
      "Supply": "3",
      "Hit Points": "600",
      "Maximum Hit Points": "600",
      "Armor Type": "Unarmored",
      "Armor": "2",
      "Maximum Armor": "8",
      "Day Sight": "140",
      "Night Sight": "80",
      "Speed": "350",
      "Build Time": "30",
      "Attack Type": "Normal",
      "Weapon Type": "Mbounce",
      "Ground Attack": "17",
      "Maximum Ground Attack": "23",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "None",
      "Maximum Air Attack": "None",
      "Cooldown": "1.8",
      "Range": "22",
      "Maximum Range": "22",
      "Race": "Night Elf",
      "Animation": "http://classic.battle.net/war3/images/nightelf/units/animations/huntress.gif",
      "Portrait": "http://classic.battle.net/war3/images/nightelf/units/portraits/huntress.gif"
    },
    "Glaive Thrower": {
      "Unit": "Glaive Thrower",
      "Gold": "210",
      "Lumber": "65",
      "Supply": "3",
      "Hit Points": "300",
      "Maximum Hit Points": "300",
      "Armor Type": "Heavy",
      "Armor": "2",
      "Maximum Armor": "2",
      "Day Sight": "140",
      "Night Sight": "120",
      "Speed": "220",
      "Build Time": "48",
      "Attack Type": "Siege",
      "Weapon Type": "Aline",
      "Ground Attack": "44.5",
      "Maximum Ground Attack": "73",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "None",
      "Maximum Air Attack": "None",
      "Cooldown": "3.5",
      "Range": "25",
      "Maximum Range": "115",
      "Race": "Night Elf",
      "Animation": "http://classic.battle.net/war3/images/nightelf/units/animations/glaivethrower.gif",
      "Portrait": "http://classic.battle.net/war3/images/nightelf/units/portraits/glaivethrower.gif"
    },
    "Dryad": {
      "Unit": "Dryad",
      "Gold": "145",
      "Lumber": "60",
      "Supply": "3",
      "Hit Points": "435",
      "Maximum Hit Points": "435",
      "Armor Type": "Unarmored",
      "Armor": "0",
      "Maximum Armor": "6",
      "Day Sight": "140",
      "Night Sight": "80",
      "Speed": "350",
      "Build Time": "30",
      "Attack Type": "Pierce",
      "Weapon Type": "Missile",
      "Ground Attack": "18",
      "Maximum Ground Attack": "24",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "18",
      "Maximum Air Attack": "24",
      "Cooldown": "2",
      "Range": "50",
      "Maximum Range": "50",
      "Race": "Night Elf",
      "Animation": "http://classic.battle.net/war3/images/nightelf/units/animations/driad.gif",
      "Portrait": "http://classic.battle.net/war3/images/nightelf/units/portraits/driad.gif"
    },
    "DoC Druid Form": {
      "Unit": "DoC Druid Form",
      "Gold": "255",
      "Lumber": "80",
      "Supply": "4",
      "Hit Points": "430",
      "Maximum Hit Points": "580",
      "Armor Type": "Heavy",
      "Armor": "1",
      "Maximum Armor": "1",
      "Day Sight": "140",
      "Night Sight": "80",
      "Speed": "270",
      "Build Time": "35",
      "Attack Type": "Normal",
      "Weapon Type": "Normal",
      "Ground Attack": "20.5",
      "Maximum Ground Attack": "25.5",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "None",
      "Maximum Air Attack": "None",
      "Cooldown": "1.5",
      "Range": "Melee",
      "Maximum Range": "Melee",
      "Race": "Night Elf",
      "Animation": "http://classic.battle.net/war3/images/nightelf/units/animations/druidclaw.gif",
      "Portrait": "http://classic.battle.net/war3/images/nightelf/units/portraits/druidclaw.gif"
    },
    "DoC Bear Form": {
      "Unit": "DoC Bear Form",
      "Gold": "N/A",
      "Lumber": "N/A",
      "Supply": "4",
      "Hit Points": "960",
      "Maximum Hit Points": "960",
      "Armor Type": "Heavy",
      "Armor": "3",
      "Maximum Armor": "9",
      "Day Sight": "140",
      "Night Sight": "80",
      "Speed": "270",
      "Build Time": "N/A",
      "Attack Type": "Normal",
      "Weapon Type": "Normal",
      "Ground Attack": "36.5",
      "Maximum Ground Attack": "47",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "None",
      "Maximum Air Attack": "None",
      "Cooldown": "1.5",
      "Range": "Melee",
      "Maximum Range": "Melee",
      "Race": "Night Elf",
      "Animation": "http://classic.battle.net/war3/images/nightelf/units/animations/druidclaw.gif",
      "Portrait": "http://classic.battle.net/war3/images/nightelf/units/portraits/druidclaw.gif"
    },
    "Mountain Giant": {
      "Unit": "Mountain Giant",
      "Gold": "425",
      "Lumber": "100",
      "Supply": "7",
      "Hit Points": "1600",
      "Maximum Hit Points": "1600",
      "Armor Type": "Medium",
      "Armor": "4",
      "Maximum Armor": "10",
      "Day Sight": "120",
      "Night Sight": "80",
      "Speed": "270",
      "Build Time": "45",
      "Attack Type": "Normal/Siege",
      "Weapon Type": "Normal",
      "Ground Attack": "34",
      "Maximum Ground Attack": "46",
      "Second Ground Attack": "41",
      "Maximum Second Ground Attack": "54.5",
      "Air Attack": "None",
      "Maximum Air Attack": "None",
      "Cooldown": "2.5",
      "Range": "Melee",
      "Maximum Range": "25",
      "Race": "Night Elf",
      "Animation": "http://classic.battle.net/war3/images/nightelf/units/animations/mountaingiant.gif",
      "Portrait": "http://classic.battle.net/war3/images/nightelf/units/portraits/mountaingiant.gif"
    },
    "Hippogryph": {
      "Unit": "Hippogryph",
      "Gold": "160",
      "Lumber": "20",
      "Supply": "2",
      "Hit Points": "525",
      "Maximum Hit Points": "525",
      "Armor Type": "Unarmored",
      "Armor": "0",
      "Maximum Armor": "6",
      "Day Sight": "160",
      "Night Sight": "80",
      "Speed": "400",
      "Build Time": "40",
      "Attack Type": "Normal",
      "Weapon Type": "Normal",
      "Ground Attack": "None",
      "Maximum Ground Attack": "None",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "53.5",
      "Maximum Air Attack": "67",
      "Cooldown": "1.05",
      "Range": "Melee",
      "Maximum Range": "Melee",
      "Race": "Night Elf",
      "Animation": "http://classic.battle.net/war3/images/nightelf/units/animations/hippogryph.gif",
      "Portrait": "http://classic.battle.net/war3/images/nightelf/units/portraits/hippogryph.gif"
    },
    "DoT Druid Form": {
      "Unit": "DoT Druid Form",
      "Gold": "135",
      "Lumber": "20",
      "Supply": "2",
      "Hit Points": "300",
      "Maximum Hit Points": "380",
      "Armor Type": "Unarmored",
      "Armor": "0",
      "Maximum Armor": "0",
      "Day Sight": "140",
      "Night Sight": "80",
      "Speed": "270",
      "Build Time": "22",
      "Attack Type": "Magic",
      "Weapon Type": "Missile",
      "Ground Attack": "12",
      "Maximum Ground Attack": "12",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "12",
      "Maximum Air Attack": "12",
      "Cooldown": "1.6",
      "Range": "60",
      "Maximum Range": "60",
      "Race": "Night Elf",
      "Animation": "http://classic.battle.net/war3/images/nightelf/units/animations/druidtalon.gif",
      "Portrait": "http://classic.battle.net/war3/images/nightelf/units/portraits/druidtalon.gif"
    },
    "DoT Crow Form": {
      "Unit": "DoT Crow Form",
      "Gold": "N/A",
      "Lumber": "N/A",
      "Supply": "2",
      "Hit Points": "300",
      "Maximum Hit Points": "380",
      "Armor Type": "Unarmored",
      "Armor": "0",
      "Maximum Armor": "6",
      "Day Sight": "160",
      "Night Sight": "80",
      "Speed": "320",
      "Build Time": "N/A",
      "Attack Type": "Magic",
      "Weapon Type": "Missile",
      "Ground Attack": "None",
      "Maximum Ground Attack": "None",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "38",
      "Maximum Air Attack": "50",
      "Cooldown": "1.75",
      "Range": "60",
      "Maximum Range": "60",
      "Race": "Night Elf",
      "Animation": "http://classic.battle.net/war3/images/nightelf/units/animations/druidtalon.gif",
      "Portrait": "http://classic.battle.net/war3/images/nightelf/units/portraits/druidtalon.gif"
    },
    "Faerie Dragon": {
      "Unit": "Faerie Dragon",
      "Gold": "155",
      "Lumber": "25",
      "Supply": "2",
      "Hit Points": "450",
      "Maximum Hit Points": "450",
      "Armor Type": "Light",
      "Armor": "0",
      "Maximum Armor": "6",
      "Day Sight": "160",
      "Night Sight": "100",
      "Speed": "350",
      "Build Time": "25",
      "Attack Type": "Pierce",
      "Weapon Type": "Missile",
      "Ground Attack": "15",
      "Maximum Ground Attack": "21",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "15",
      "Maximum Air Attack": "21",
      "Cooldown": "1.75",
      "Range": "30",
      "Maximum Range": "30",
      "Race": "Night Elf",
      "Animation": "http://classic.battle.net/war3/images/nightelf/units/animations/faeriedragon.gif",
      "Portrait": "http://classic.battle.net/war3/images/nightelf/units/portraits/faeriedragon.gif"
    },
    "Hippogryph Rider": {
      "Unit": "Hippogryph Rider",
      "Gold": "N/A",
      "Lumber": "N/A",
      "Supply": "4",
      "Hit Points": "765",
      "Maximum Hit Points": "765",
      "Armor Type": "Light",
      "Armor": "1",
      "Maximum Armor": "",
      "Day Sight": "160",
      "Night Sight": "80",
      "Speed": "350",
      "Build Time": "N/A",
      "Attack Type": "Pierce",
      "Weapon Type": "Missile",
      "Ground Attack": "17",
      "Maximum Ground Attack": "26",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "17",
      "Maximum Air Attack": "26",
      "Cooldown": "1.1",
      "Range": "40",
      "Maximum Range": "60",
      "Race": "Night Elf",
      "Animation": "http://classic.battle.net/war3/images/nightelf/units/animations/hippogryphrider.gif",
      "Portrait": "http://classic.battle.net/war3/images/nightelf/units/portraits/hippogryphrider.gif"
    },
    "Chimaera": {
      "Unit": "Chimaera",
      "Gold": "330",
      "Lumber": "70",
      "Supply": "5",
      "Hit Points": "1000",
      "Maximum Hit Points": "1000",
      "Armor Type": "Light",
      "Armor": "2",
      "Maximum Armor": "8",
      "Day Sight": "160",
      "Night Sight": "80",
      "Speed": "250",
      "Build Time": "65",
      "Attack Type": "Magic/Siege",
      "Weapon Type": "Msplash/Missile",
      "Ground Attack": "75",
      "Maximum Ground Attack": "102",
      "Second Ground Attack": "50",
      "Maximum Second Ground Attack": "68",
      "Air Attack": "None",
      "Maximum Air Attack": "None",
      "Cooldown": "2.5",
      "Range": "45",
      "Maximum Range": "85",
      "Race": "Night Elf",
      "Animation": "http://classic.battle.net/war3/images/nightelf/units/animations/chimaera.gif",
      "Portrait": "http://classic.battle.net/war3/images/nightelf/units/portraits/chimaera.gif"
    },
    "Treant": {
      "Unit": "Treant",
      "Gold": "N/A",
      "Lumber": "N/A",
      "Supply": "N/A",
      "Hit Points": "300",
      "Maximum Hit Points": "300",
      "Armor Type": "Heavy",
      "Armor": "0",
      "Maximum Armor": "5",
      "Day Sight": "120",
      "Night Sight": "80",
      "Speed": "220",
      "Build Time": "N/A",
      "Attack Type": "Normal",
      "Weapon Type": "Normal",
      "Ground Attack": "16",
      "Maximum Ground Attack": "16",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "None",
      "Maximum Air Attack": "None",
      "Cooldown": "1.75",
      "Range": "Melee",
      "Maximum Range": "Melee",
      "Race": "Night Elf",
      "Animation": "http://classic.battle.net/war3/images/nightelf/units/animations/ent.gif",
      "Portrait": "http://classic.battle.net/war3/images/nightelf/units/portraits/ent.gif"
    },
    "Avatar of Vengeance": {
      "Unit": "Avatar of Vengeance",
      "Gold": "N/A",
      "Lumber": "N/A",
      "Supply": "N/A",
      "Hit Points": "1200",
      "Maximum Hit Points": "1200",
      "Armor Type": "Heavy",
      "Armor": "2",
      "Maximum Armor": "2",
      "Day Sight": "120",
      "Night Sight": "100",
      "Speed": "320",
      "Build Time": "N/A",
      "Attack Type": "Normal",
      "Weapon Type": "Missile",
      "Ground Attack": "30.5",
      "Maximum Ground Attack": "30.5",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "30.5",
      "Maximum Air Attack": "30.5",
      "Cooldown": "1.35",
      "Range": "45",
      "Maximum Range": "45",
      "Race": "Night Elf",
      "Animation": "http://classic.battle.net/war3/images/nightelf/units/animations/avatarofvengeance.gif",
      "Portrait": "http://classic.battle.net/war3/images/nightelf/units/portraits/avatarofvengeance.gif"
    },
    "Spirit of Vengeance": {
      "Unit": "Spirit of Vengeance",
      "Gold": "N/A",
      "Lumber": "N/A",
      "Supply": "N/A",
      "Hit Points": "500",
      "Maximum Hit Points": "500",
      "Armor Type": "Invulnerable",
      "Armor": "Invulnerable",
      "Maximum Armor": "Invulnerable",
      "Day Sight": "120",
      "Night Sight": "80",
      "Speed": "270",
      "Build Time": "N/A",
      "Attack Type": "Pierce",
      "Weapon Type": "Missile",
      "Ground Attack": "16",
      "Maximum Ground Attack": "16",
      "Second Ground Attack": "None",
      "Maximum Second Ground Attack": "None",
      "Air Attack": "16",
      "Maximum Air Attack": "16",
      "Cooldown": "1.35",
      "Range": "45",
      "Maximum Range": "45",
      "Race": "Night Elf",
      "Animation": "http://classic.battle.net/war3/images/nightelf/units/animations/spiritofvengeance.gif",
      "Portrait": "http://classic.battle.net/war3/images/nightelf/units/portraits/spiritofvengeance.gif"
    }
  }
}

//  const racearray = Object.entries(data['Undead']['Buildings']);
// for (let i = 0; i < racearray.length; i++) {
//           let building = racearray[i][0].replace(" ", "").replace(" ", "").toLowerCase();
//           window.open(`http://classic.battle.net/war3/undead/buildings/${building}.shtml`,'_blank');

//     }  
export default data;
